### PR TITLE
Fix scripts

### PR DESCRIPTION
**Pull request by JulianGCalderon**

### CODE REVIEW

**Comment by tomyrd** [comment]
Im adding the fix for #83 here as it's a fix on the deployment scripts

**Review by JulianGCalderon — COMMENTED** [review]
Were you able to test in testing-blockchain?

**Comment by tomyrd** [comment]
After fixing the network the scripts work fine.

**Review by fborello-lambda — APPROVED** [review]

**Review by JulianGCalderon — COMMENTED** [review]
LGTM (can't approve, as I created the PR)

**Comment by ManuelBilbao** [comment]
Is this script only intended for us? Otherwise, the `/home/admin` path would be better to be in an envvar

**Comment by tomyrd** [comment]
> Is this script only intended for us? Otherwise, the `/home/admin` path would be better to be in an envvar

Yes, the `server_node_setup.sh` script is meant for internal use only.

**Review by ManuelBilbao — APPROVED** [review]
LGTM

**Pull request merged**
