### PR TITLE
Add additional staking info

### PR DESCRIPTION
**Pull request by GabrielSac**
Add command to stake even after becoming a validator.

### CODE REVIEW

**Review by ManuelBilbao — COMMENTED** [review]
Should we add how to obtain `valoperaddr`?

**Comment by JulianGCalderon** [comment]
> Should we add how to obtain `valoperaddr`?

I think we should.

**Comment by GabrielSac** [comment]
I thought it was somewhere in the readme, but it seems it's not. Could you add it? We also need to change addresses in the readme from "cosmos" to aligned

**Comment by ManuelBilbao** [comment]
I'm on it

**Review by ManuelBilbao — APPROVED** [review]

**Review by GabrielSac — COMMENTED** [review]
LGTM

**Review by tomyrd — APPROVED** [review]
LGTM

**Pull request merged**
