### PR TITLE
Change address prefix

### PR DESCRIPTION
**Pull request by GabrielSac**
Changed addresses prefixes (instead of "cosmosxxxxxx", "alignedxxxxxx").

### CODE REVIEW

**Review by JulianGCalderon — COMMENTED** [review]
Does it also change the validator and operator address?

**Comment by GabrielSac** [comment]
> Does it also change the validator and operator address?

Yes, it changes a prefix variable which is used for all addresses. So cosmosvaloperxxxxx is now alignedvaloperxxxxx

**Review by JulianGCalderon — APPROVED** [review]
LGTM

**Review by tomyrd — APPROVED** [review]
Tested it and it works. LGTM.

**Pull request merged**
