### PR TITLE
Add Plonk verification

### PR DESCRIPTION
**Pull request by fborello-lambda**
- Add Support for base64 Serialization. 
- Added Plonk verification with support for serialization in the MsgVerify.

### CODE REVIEW

**Comment by GabrielSac** [comment]
Added Plonk verification with support for serialization in the MsgVerify.
Currently setup is done on a simple circuit. The verifying key is obtained and then hardcoded.

**Review by ManuelBilbao — DISMISSED** [review]
LGTM 👍🏻

**Comment by ManuelBilbao** [comment]
@fborello-lambda I think this PR should not close #12 issue because it's not integrated with the app yet

**Comment by JulianGCalderon** [comment]
Outdated by #26

**Pull request closed without merging**
